services:
  mongoDB:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - migrationData:/data/db

  backend:
    depends_on: [ mongoDB ]
    build:
      context: ./code/backend
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "10086:10086"

  frontend:
    depends_on: [ backend ]
    build:
      context: ./code/frontend
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "3000:3000"

  migration_worker:
    depends_on: [ frontend ]
    build:
      context: ./code/migrationWorker
      dockerfile: ./Dockerfile
    env_file: .env

  synchronization_worker:
    depends_on: [ frontend ]
    build:
      context: ./code/synchronizationWorker
      dockerfile: ./Dockerfile
    env_file: .env

volumes:
  migrationData: { }