version: "3.9"
services:
  fast-stream:
    image: fast-stream
    volumes:
      - fs-logs:/usr/src/app/server/logs
      - fs-data:/usr/src/app/server/data
    environment:
      AWS_REGION: 
      AWS_SECRET_ACCESS_KEY: 
      AWS_ACCESS_KEY_ID: 
      AWS_ENDPOINT:
      PORT: 5000
    ports:
      - "5000:5000"
volumes:
  fs-logs:
  fs-data: